### ISSUE TITLE
我的nexus6 6.0.1系统，安装你的apk，会闪退

### ISSUE THREAD

**Issue by moerfutin** [ifchen0/IITC_TW#1]
如题，无法使用。第一次我覆盖安装了原版，可以使用，当重启了一次手机后，就再也用不了了。无论我卸载，清除数据，再安装都无济于事。求解决方法

**Comment by moerfutin** [comment]
![screenshot_20161009-083256](https://cloud.githubusercontent.com/assets/9960618/19216726/0e6cd10a-8d8e-11e6-8827-c5114f03c8ab.png)

**Comment by ifchen0** [comment]
儲存空間根目錄的IITC_Mobile資料夾砍掉看看
我猜可能有些外掛不相容？

**Comment by moerfutin** [comment]
根目录木有这个文件夹呀，nexus6是内置存储没有外置存储卡呀。 根目录没有，那么是在/data/目录下吗

**Comment by ifchen0** [comment]
我自己是用Nexus5 Android 6.0.1

也許試試較早的版本??
https://github.com/ifchen0/IITC_TW/blob/509369f4186af12a2aca2b6b9f39bcf31cdaca38/build/mobile/IITC_Mobile-debug.apk

**Comment by moerfutin** [comment]
0.25.2 覆盖安装后可以打开，但是重启手机又不行了。跟我手机root 装了xposed有关系吗，还是说那里有错误日志可以提取？多谢！

**Comment by moerfutin** [comment]
原版的IITC 0.25.2 不存在这个问题。我就想用IITC-tw 里的plugins 脚本，如果有办法用❴原版IITC+ IITC _TW的外挂❵也可以，不知可行不？

**Comment by ifchen0** [comment]
IITCm和IITC應該是使用同樣的plug-in，一般plug-in可以直接用IITCm開啟來安裝。
main-plugin的話可能要儲存在 sdcard/IITC_Mobild/dev/ 目錄下，並啟用Advance裡的"開發人員模式"來執行。

官方0.25.2看起來是在2015/11/11 build的，雖然版號相同，但這期間改了不少東西 @@
如果下面這版也不行的話，可能就是我這邊亂改到什麼了。
https://github.com/ifchen0/IITC_TW/blob/11ee32deb8487444bdb9a520f535a0149bc8958e/build/mobile/IITC_Mobile-debug.apk?raw=true

**Comment by moerfutin** [comment]
装了build/Mobile 里最新的就可以，再也不闪退了！感谢开发者！ 楼上的这个apk我还没试，看了md5是和release最新的apk不一样的

**Comment by ifchen0** [comment]
嗯，最新的這版有新合併一些官方的code，如果沒問題的話就先close了。
